---

- name: ensure tasks run only on selected os releases
  block:

    - name: prevent sleep when laptop lid is closed - on battery
      ansible.builtin.lineinfile:
        path: /etc/systemd/logind.conf
        regexp: '^.*#HandleLidSwitch='
        line: HandleLidSwitch=ignore

    - name: prevent sleep when laptop lid is closed - on power
      ansible.builtin.lineinfile:
        path: /etc/systemd/logind.conf
        regexp: '^.*#HandleLidSwitchExternalPower='
        line: HandleLidSwitchExternalPower=ignore

    - name: prevent sleep when laptop lid is closed - when docked
      ansible.builtin.lineinfile:
        path: /etc/systemd/logind.conf
        regexp: '^.*#HandleLidSwitchDocked='
        line: HandleLidSwitchDocked=ignore

    - name: configure additional grub menu tweaks
      ansible.builtin.include_role:
        name: mgmt__grub
        tasks_from: grub_settings.yml
      vars:
        grub_setting: "{{ grub.menu }}"
        grub_task: configure

  when: >
    ansible_distribution == "CentOS" or
    ansible_distribution == "Fedora" or
    ansible_distribution == "RedHat" or
    ansible_distribution == "Rocky"

...
